---

- name: Gather network facts
  ansible.builtin.setup:
    gather_subset:
      - network
  when: ansible_all_ipv4_addresses is not defined

- name: Debug ansible_all_ipv4_addresses
  ansible.builtin.debug:
    var: ansible_all_ipv4_addresses

# Get docker0 interface IP if it exists
- name: Get docker0 interface IP
  ansible.builtin.set_fact:
    docker0_ip: "{{ ansible_docker0.ipv4.address | default('') }}"
  when: ansible_docker0 is defined and ansible_docker0.ipv4 is defined

# Define bind_address for each host (first private IPv4, excluding docker0), unless set in inventory.
- name: Expose bind_address as facts
  ansible.builtin.set_fact:
    bind_address: >-
      {{
        (
          ansible_all_ipv4_addresses | default([])
          | ansible.utils.ipaddr('private')
          | reject('equalto', docker0_ip | default(''))
          | list
        )[0] | default('')
      }}
  when: bind_address is not defined

- name: No suitable bind_address found
  ansible.builtin.fail:
    msg: "No suitable private ip address found!"
  when: bind_address == ''
